---
apiVersion: helm.fluxcd.io/v1
kind: HelmRelease
metadata:
  name: code-server
  namespace: code-server
spec:
  releaseName: code-server
  chart: 
    git: https://github.com/cdr/code-server.git
    tag: v3.8.0
    path: ci/helm-chart
values:
  ingress:
    enabled: true
    annotations:
      kubernetes.io/ingress.class: nginx
      kubernetes.io/tls-acme: "true"
      forecastle.stakater.com/expose: "true"
      forecastle.stakater.com/appName: "hacksm.net"
      forecastle.stakater.com/icon: https://avatars0.githubusercontent.com/u/6154722
      forecastle.stakater.com/group: "Code"
      kubernetes.io/ingress.class: "nginx"
    hosts:
      - host: code-wiki.hacksm.net
        paths:
          - /
  persistence:
    enabled: true
    storageClass: hcloud-volumes
  extraContainers:
  - env:
    - name: GIT_SYNC_REPO
      value: https://github.com/krangence/code-wiki.git
    - name: GIT_SYNC_DEST
      value: git
    - name: GIT_SYNC_WAIT
      value: '10'
    - name: GIT_SYNC_SSH
      value: 'true'
    - name: GIT_SSH_KEY_FILE
      value: /var/ssh/sshkey
    - name: GIT_SSH_KNOWN_HOSTS_FILE
      value: /var/knownhosts/known_hosts
    image: 'k8s.gcr.io/git-sync:v3.1.1@sha256:aa701af5a29738f4a7aa1686f189787d92cea6401e0e81a170e98b10d365a949'
    name: git-sync
    volumeMounts:
    - mountPath: /var/ssh
      name: ssh-key
    - mountPath: /var/knownhosts
      name: known-hosts
    - mountPath: /home/coder
      name: git-sync-volume
  extraVolumeMounts:
  - mountPath: /var/ssh
    name: ssh-key
    readOnly: true
  - mountPath: /var/knownhosts
    name: known-hosts
    readOnly: true
  - mountPath: /home/coder
    name: git-sync-volume
  extraVolumes:
  - name: ssh-key
    secret:
      items:
      - key: key
        path: sshkey
      secretName: dags-secret
  - name: known-hosts
    secret:
      items:
      - key: known_hosts
        path: known_hosts
      secretName: dags-secret
  - emptyDir: {}
    name: git-sync-volume
