---
apiVersion: helm.fluxcd.io/v1
kind: HelmRelease
metadata:
  name: rr5
  namespace: mc
spec:
  releaseName: rr5
  chart:
    git: git@github.com:HRZNStudio/playhrzn-k8s
    ref: master
    path: charts/minecraft
  values:
    # ref: charts/minecraft/values.yaml
    domain: playhrzn.com
    minecraftServer:
      image: itzg/minecraft-server:latest@sha256:0967be81d86919969c63fe6888040836cdfc1c70cae51b37221c225312dc7d97
      eula: "TRUE"
      version: "1.12.2"
      type: "FORGE"
      forgeVersion: "14.23.5.2847"
      maxtickTime: -1
      memory: 8G
      rconWebAdmin:
        image: cwlf/rcon:latest@sha256:e6d0d325f9686c00f8b4b50afd9ef7a03a5bf0c305e7567db008d8679163c6b1
        websocketUrlSsl: "wss://rr5-rwa-ws.playhrzn.com"
        webIngress:
          hostname: rr5-rwa.playhrzn.com
          annotations:
            ingress.pomerium.io/allowed_domains: '["chipwolf.uk", "hrznstudio.com"]'
            forecastle.stakater.com/expose: "true"
            forecastle.stakater.com/icon: https://brainfoolong.github.io/rcon-web-admin/images/logo.png
            forecastle.stakater.com/appName: "RCON Web Admin"
            forecastle.stakater.com/group: "rr5"
        websocketIngress:
          hostname: rr5-rwa-ws.playhrzn.com
          annotations:
            kubernetes.io/ingress.class: "nginx"
      cloudCommander:
        image: coderaiser/cloudcmd:14.6.0-alpine@sha256:f0fbdbac4058cf075988119a54965c1f822f01cd1082260fc5cb5eb4d6464f65
        ingress:
          hostname: rr5-files.playhrzn.com
          annotations:
            ingress.pomerium.io/allowed_domains: '["chipwolf.uk", "hrznstudio.com"]'
            forecastle.stakater.com/expose: "true"
            forecastle.stakater.com/icon: https://cloudcmd.io/img/logo/cloudcmd.png
            forecastle.stakater.com/appName: "File Manager"
            forecastle.stakater.com/group: "rr5"
    extraEnv:
      GENERIC_PACK: "https://cdn.hrzn.studio/rr5-server-staging.zip"
      GENERIC_PACK_STRIP_DIRS: "0"
      OVERRIDE_SERVER_PROPERTIES: "1"
      USE_AIKAR_FLAGS: "1"
    persistence:
      volumeName: pvc-bc6ba9b7-c4ce-425b-b300-6b21d83df743
---
apiVersion: "autoscaling.k8s.io/v1beta2"
kind: VerticalPodAutoscaler
metadata:
  name: rr5-vpa
spec:
  targetRef:
    apiVersion: "apps/v1"
    kind: Deployment
    name: mc-rr5-minecraft
  resourcePolicy:
    containerPolicies:
      - containerName: '*'
        minAllowed:
          cpu: 200m
          memory: 7168Mi
        maxAllowed:
          cpu: 2
          memory: 8Gi
        controlledResources: ["cpu", "memory"]
