---
steps:
  - name: gcr.io/cloud-builders/git
    args: [init]

  - name: gcr.io/cloud-builders/git
    args: [remote, add, origin, git@github.com:HRZNStudio/playhrzn-k8s.git]

  - name: quay.io/helmpack/chart-testing:v2.4.1
    args: [ct, lint, --all, --debug, --chart-dirs, charts]

  - name: garethr/kubeval:0.15.0
    args: [-d, 'base,flux', -i, '.flux.yaml,cloudbuild.yaml,kustomization.yaml,patch.yaml,^*.-crd.yaml$', --skip-kinds, 'HelmRelease,SealedSecret,VerticalPodAutoscaler']

  - name: cytopia/yamllint:1.23
    args: ['.']
