---
apiVersion: helm.fluxcd.io/v1
kind: HelmRelease
metadata:
  name: kube-ops-view
  namespace: monitoring
spec:
  releaseName: kube-ops-view
  chart:
    repository: https://kubernetes-charts.storage.googleapis.com/
    name: kube-ops-view
    version: 1.1.4
  values:
    rbac:
      create: true
    ingress:
      enabled: true
      annotations:
        kubernetes.io/ingress.class: "nginx"
        external-dns.alpha.kubernetes.io/hostname: ops.hacksm.net
