---
apiVersion: helm.fluxcd.io/v1
kind: HelmRelease
metadata:
  name: kube-ops-view
  namespace: monitoring
spec:
  releaseName: kube-ops-view
  chart:
    repository: https://kubernetes-charts.storage.googleapis.com/
    name: kube-ops-view
    version: 1.1.4
  values:
    rbac:
      create: true
    ingress:
      enabled: true
      annotations:
        forecastle.stakater.com/expose: "true"
        forecastle.stakater.com/appName: "Kube Ops View"
        forecastle.stakater.com/icon: 'https://hub.helm.sh/api/chartsvc/v1/assets/stable/kube-ops-view/logo'
        kubernetes.io/ingress.class: "nginx"
        external-dns.alpha.kubernetes.io/hostname: ops.hacksm.net
