---
apiVersion: helm.fluxcd.io/v1
kind: HelmRelease
metadata:
  name: kibana
  namespace: elastic-stack
spec:
  releaseName: kibana
  chart:
    repository: https://helm.elastic.co
    name: kibana
    version: 7.7.1
  values:
    ingress:
      enabled: true
      hosts: ["kibana.playhrzn.com"]
      annotations:
        ingress.pomerium.io/allowed_domains: '["chipwolf.uk", "hrznstudio.com"]'
        forecastle.stakater.com/expose: "true"
        forecastle.stakater.com/icon: https://github.com/stakater/ForecastleIcons/raw/master/kibana.png
        forecastle.stakater.com/appName: "Kibana"
        forecastle.stakater.com/group: "monitoring"
