---
apiVersion: helm.fluxcd.io/v1
kind: HelmRelease
metadata:
  name: logstash
  namespace: elastic-stack
spec:
  releaseName: logstash
  chart:
    repository: https://helm.elastic.co
    name: logstash
    version: 7.7.0
  values:
    service:
      annotations: {}
      type: ClusterIP
      ports:
        - name: beats
          port: 5044
          protocol: TCP
          targetPort: 5044
        - name: http
          port: 8080
          protocol: TCP
          targetPort: 8080
