---
apiVersion: helm.fluxcd.io/v1
kind: HelmRelease
metadata:
  name: kong
  namespace: kong
spec:
  releaseName: kong
  chart:
    repository: https://charts.konghq.com
    name: kong
    version: 1.7.0
  values:
    ingress:
      enabled: true
      hostname: api.hacksm.net
  ingressController:
      enabled: true
      installCRDs: false
