---
apiVersion: helm.fluxcd.io/v1
kind: HelmRelease
metadata:
  name: pomerium
  namespace: pomerium
spec:
  releaseName: pomerium
  chart:
    repository: https://helm.pomerium.io
    name: pomerium
    version: 9.0.0
  valuesFrom:
    - secretKeyRef:
        name: pomerium-values
  values:
    ingress:
      annotations:
        kubernetes.io/ingress.class: "nginx"
        kubernetes.io/ingress.allow-http: "false"
        external-dns.alpha.kubernetes.io/hostname: 'forwardauth.hacksm.net,authorize.hacksm.net,authenticate.hacksm.net'
        nginx.ingress.kubernetes.io/backend-protocol: "HTTPS"
        nginx.ingress.kubernetes.io/proxy-buffer-size: "16K"
    forwardAuth:
      enabled: false
    service:
      type: NodePort
    config:
      rootDomain: hacksm.net
      policy:
        - from: https://ops.hacksm.net
          to: http://kube-ops-view.monitoring.svc.cluster.local
          allowed_users:
            - matt@matt-white.co.uk
          allow_websockets: true
        - from: https://kibana.hacksm.net
          to: http://kibana-kibana.elastic-stack.svc.cluster.local:5601
          allowed_users:
            - matt@matt-white.co.uk
    operator:
      enabled: true
