---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  creationTimestamp: null
  name: pomerium-values
  namespace: pomerium
spec:
  encryptedData:
    values.yaml: AgAsTNyKEKzd1AZJFt/qljFa4vtA1lxnn7k+1AXx/0JkQp56jM2NZVEv/WBADwceujRfbpg/GTEHcrJ/gmLrkWCedcANVR7Z25B3fNKKxhcrcMSIAn1uh4FXxk/exwOKmPLokctVwRcsULCNLhmx2ABpZ/bLj4hbp0MXv5YTfHFaC/QPrm04gPLvzJvxeJEKeH5jBJQwP/P82m67beNsrVXbdnYO/X/xq5E9yLyK74aplWTedC/qoPCw/GO5W97ImUAwP1oarvu6jo29nA5jL2Qdvgr2iaIJZVnCt0Tp0hCLOhD/nQYEtLEekESpuBrbJBJq2Ydw/6dZDvfxp4GJY/skY38KP3y7+del8DM4NGDDcLd3UFYvzsIn6zgRw9/dZRLmVglOPNuwTuT9tI/nFYBEwhQQNWIj1+Uwrq+b+eOTWQQsRt0zf/4omqkyjhbToYbiXFEgj7HCPvoMEt1QDvgZhIyH6Ty/EZ7LmWDvqGj34ocD5y/+WNPlJWxtznCtlpub7rc/udkGRMpY9SK+uMMmzOO+2Z9KngdiHyBpxAEm5z8mm8QRbzHtD10efXEhebqWQuxdEiYZcCImxS39yPGEop4MIHuPzL4HCZFyN/YfSXimhVivHwIbGsKFP3/5hDn2SMTkTcW2/Z4Qkl/mDbXwnFgtgrEuxo+HPlTYPM49y+ttnFsHzTQQJVFRTNvwBJFJFVMpImOO98OdX4YPMovGFxIZFzYDjZJQedXztoQ7uTZH9PHXS4FeREnwKgmqt8QURQSwcvoVsI7pVBfV+Drem3WOkQNXpu/iq2FzTRHpFY16hu6sZJ1Zqth9xhHMAjMoN+fx2PlGIZtC4vJabP9uv18zrCnb1OENXT/NXn9mYA2uWGcxkp+guK96P/1VZr6HCTbD/HRejmjieIejD9xWKtNrqvyDZWHNpzRQJdipdGCijZKGFCU3yuaFbbsSSbBKMnxqBynUypbVFZb7GG8ddr4LAj3BAKn7owIp+RSlctcFt4+CgQdnoixw7Fd0bmMkm1hgRkpSX86IIKSYN507Xm3hOy0v2PHaYb8PU6/krfaGyOqOIX0R7jH3fyr9b1noyxRmpLopmadWlt2Z+01W30DIR/b1M6IWtrmrt+sV7XvblHJA9YMRfEJsWfYE1eKCJ1tjg72grqYlPRg5CHUEukxnXptmXjC9Cr+VQXJtHuQx2nJuGFzoqHqWdEemtAKadgdiPVhFKYOVgNrvy1uorY8KcAg6G/a00omnGI7k8BPRWUvUCBs=
  template:
    metadata:
      creationTimestamp: null
      name: pomerium-values
      namespace: pomerium
