---
apiVersion: helm.fluxcd.io/v1
kind: HelmRelease
metadata:
  name: ingress-nginx
  namespace: ingress-nginx
spec:
  releaseName: ingress-nginx
  chart:
    repository: https://kubernetes.github.io/ingress-nginx/
    name: ingress-nginx
    version: 3.8.0
  values:
    fullnameOverride: ingress-nginx
    controller:
      admissionWebhooks:
        enabled: false
      extraArgs:
        default-ssl-certificate: "kube-system/acme-crt-secret"
      updateStrategy:
        type: Recreate
      config:
        global-auth-signin: https://forwardauth.hacksm.net/?uri=$scheme://$host$request_uri
        global-auth-url: https://forwardauth.hacksm.net/verify?uri=$scheme://$host$request_uri
        use-forwarded-headers: "true"
        force-ssl-redirect: "true"
