---
apiVersion: cert-manager.io/v1
kind: ClusterIssuer
metadata:
  name: letsencrypt-prod
spec:
  acme:  
    server: https://acme-v02.api.letsencrypt.org/directory  
    email: matt@matt-white.co.uk  
    privateKeySecretRef:
      name: letsencrypt-prod
    solvers:
      dns01:
        providers:
        - name: route53-dns
          route53:
            accessKeyID: AKIAW4YYMLNFPKMOL6GO
            region: us-east-1
            secretAccessKeySecretRef:
              name: route53-credentials
              key: aws-secret-access-key
