apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  creationTimestamp: null
  name: route53-credentials
  namespace: cert-manager
spec:
  encryptedData:
    aws-secret-access-key: AgAn8ht/QivDN1yLu5rkq/h2ELDIcTPBmRhezbWb4MpcLhKW0C5KXHXDQFMd4aVNjhmKcmwpc36zLzcaxoLR/7XMqQcUEnv1P8utZ1oc2mvQbAxsUX/PiZcj3T91gWGnmDpkMfrJijK2Lm7tUZXusjb68irJ5XshavZw+eFaho7egyBudpOvxFDdQtCAiD2Tfmy/wPxKmpICu6E0uRZtovaQE9xAleUJiPCm0NTdxY9mcYVM663C4U9KM8Gz644dTf3ayAuxBpgQsZtO0afMRmfNB0ObGBeFhaWXk7NDa8GtMZlqNsvD66xkkSLqCIjXbXwb5otK9SnqHjjarWhevd4zKCm+i8SA55Z+COc6PS3sgOn5gjfltRxwe8xbFwou3pG/4Uo3Ucffu7JnVhbhJEulKYKKjluPd/RfwYrmJSxpPA5yN/9Yfg2NxdTL8M2uO3MLXMoOqhgtAQZiqwaN0zSS3I4IveaXlDFFEqy/VzKUC1RKpMvkB8Y85JGjJwkOOjixy4XCp3iCIv1XcnabQcLeFqSYJJ5ex/yO8IhloOCtbGWW/PK9TdLa9gqm7hqWe12FOyjQAZ1E7jjLA4monLQn9uIJeVDw6TX2G084KS3G8xWrgXCC4RlgCViVHcEOUm4vqyqfZqJ6Bs+j+TUqAtyV6MrZu8gAE/BUaTpbqPQAtL0Lqdh4KXhGBHGn9SIXQmKg3dlRwoacN4H+xMGB/V60/k47tRy+OOCWY/Y8N3XkaZSyqVDBlkN8
  template:
    metadata:
      creationTimestamp: null
      name: route53-credentials
      namespace: cert-manager
