--- 
apiVersion: helm.fluxcd.io/v1
kind: HelmRelease
metadata: 
  name: velero
  namespace: velero
spec: 
  chart: 
    name: velero
    repository: "https://vmware-tanzu.github.io/helm-charts"
    version: "2.12.13"
  releaseName: velero
  valueFileSecrets: 
  - name: velero-helm-values
  values: 
    configuration: 
      backupStorageLocation: 
        bucket: velero
        config: 
          publicUrl: "https://minio.hacksm.net"
          region: us-east-1
          s3ForcePathStyle: true
          s3Url: "http://minio.default.svc:9000"
        name: default
      provider: aws
      resticTimeout: 6h
      volumeSnapshotLocation:
        name: aws
        config:
          region: us-east-1
    deployRestic: true
    initContainers: 
    - image: "velero/velero-plugin-for-aws:v1.1.0@sha256:e52d3545c3c52dbd061f0bf2ae8f7d6b21747d0a8bc64245fb58c8de54df9b33"
      imagePullPolicy: IfNotPresent
      name: velero-plugin-for-aws
      volumeMounts: 
      - mountPath: /target
        name: plugins
    schedules: 
      daily-backup: 
        schedule: "0 6 * * *"
        template: 
          ttl: 120h
    snapshotsEnabled: false
