---
apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: nitetech
  namespace: default
spec:
  interval: 5m
  chart:
    spec:
      chart: nginx
      version: 8.5.3
      sourceRef:
        kind: HelmRepository
        name: bitnami-charts
        namespace: flux-system
      interval: 5m
  values:   
    service:
      type: ClusterIP
    cloneStaticSiteFromGit:
      enabled: true
      repository: "https://github.com/krangence/nitetech.co.uk.git"
      branch: "main"
    ingress: 
      enabled: true
      annotations:
        forecastle.stakater.com/expose: "true"
        forecastle.stakater.com/appName: "nitetech.co.uk"
        forecastle.stakater.com/icon: https://avatars0.githubusercontent.com/u/1412239
        forecastle.stakater.com/group: "HACKSM"
        kubernetes.io/ingress.class: "nginx"
        nginx.ingress.kubernetes.io/enable-global-auth: "false"
      hostname: "nitetech.co.uk"
    