---
apiVersion: helm.fluxcd.io/v1
kind: HelmRelease
metadata:
  name: external-dns
  namespace: external-dns
spec:
  releaseName: external-dns
  chart:
    repository: https://charts.bitnami.com/bitnami
    name: external-dns
    version: 3.7.0
  valuesFrom:
    - secretKeyRef:
        name: external-dns-values
  values:
    domainFilters: ["hacksm.net", "matt-white.co.uk", "nitetech.co.uk"]
    policy: sync
    aws:
      credentials:
        accessKey: AKIAW4YYMLNFPY4BD76X
    txtPrefix: hacksm
